name = "BACAP Hardcore"
filename = "bacap_hardcore.zip"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/QEv1xmKi/versions/uRKM9Bou/BlazeandCave%27s%20Advancements%20Pack%20Hardcore.zip"
hash-format = "sha1"
hash = "ec5203496a822e6145562cd81e781ca0eea2c968"

[update]
[update.modrinth]
mod-id = "QEv1xmKi"
version = "uRKM9Bou"
