hash-format = "sha256"

[[files]]
file = "config/betterf3.json"

[[files]]
file = "config/citresewn.json"

[[files]]
file = "config/custom-hud/profile1.txt"

[[files]]
file = "config/dark-loading-screen.json"

[[files]]
file = "config/debugify.json"

[[files]]
file = "config/isxander-main-menu-credits.json"

[[files]]
file = "config/modmenu.json"

[[files]]
file = "config/yosbr/config/blur.json"

[[files]]
file = "config/yosbr/config/capes.json5"

[[files]]
file = "config/yosbr/config/custom-hud/config.json"

[[files]]
file = "config/yosbr/config/dynamicfps.toml"

[[files]]
file = "config/yosbr/config/fallingleaves.json"

[[files]]
file = "config/yosbr/config/firstperson.json"

[[files]]
file = "config/yosbr/config/iris.properties"

[[files]]
file = "config/yosbr/config/lambdynlights.toml"

[[files]]
file = "config/yosbr/config/moreculling.toml"

[[files]]
file = "config/yosbr/config/shulkerboxtooltip.json5"

[[files]]
file = "config/yosbr/config/sodium-extra-options.json"

[[files]]
file = "config/yosbr/config/sodium-options.json"

[[files]]
file = "config/yosbr/options.txt"

[[files]]
file = "datapacks/blazeandcaves-advancements-pack.pw.toml"
metafile = true

[[files]]
file = "icon.png"

[[files]]
file = "mods/achievetodo-mc1.20.4+1.3.jar"

[[files]]
file = "mods/antighost.pw.toml"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
metafile = true

[[files]]
file = "mods/blur.pw.toml"
metafile = true

[[files]]
file = "mods/boat-break-fix.pw.toml"
metafile = true

[[files]]
file = "mods/c2me.pw.toml"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
metafile = true

[[files]]
file = "mods/cursorcentered-fix.pw.toml"
metafile = true

[[files]]
file = "mods/customhud.pw.toml"
metafile = true

[[files]]
file = "mods/dark-loading-screen.pw.toml"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
metafile = true

[[files]]
file = "mods/extra-sounds.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
metafile = true

[[files]]
file = "mods/fabricskyboxes.pw.toml"
metafile = true

[[files]]
file = "mods/fallingleaves.pw.toml"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
metafile = true

[[files]]
file = "mods/fixbookgui.pw.toml"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
metafile = true

[[files]]
file = "mods/language-reload.pw.toml"
metafile = true

[[files]]
file = "mods/libjf.pw.toml"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
metafile = true

[[files]]
file = "mods/main-menu-credits.pw.toml"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
metafile = true

[[files]]
file = "mods/no-resource-pack-warnings.pw.toml"
metafile = true

[[files]]
file = "mods/real-arrow-tip.pw.toml"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
metafile = true

[[files]]
file = "mods/respackopts.pw.toml"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
metafile = true

[[files]]
file = "mods/screenshot-to-clipboard.pw.toml"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
metafile = true

[[files]]
file = "mods/textile-backup.pw.toml"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/Better Banner Pattern.zip"

[[files]]
file = "resourcepacks/Better Waxed Copper.zip"

[[files]]
file = "resourcepacks/Model Optimizations & Fixes.zip.rpo"

[[files]]
file = "resourcepacks/Visual Fish Buckets.zip"

[[files]]
file = "resourcepacks/Visual Goat Horns.zip"

[[files]]
file = "resourcepacks/bacap-language-pack.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/barrel-fix.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/bettergrass.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/centered-crosshair-fix.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/chiseled-stone-bricks.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/colorful-sheared-sheep.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/ctm-overhaul.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/default-dark-mode.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/hardcore-absorption-fix.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/map-marking-fix.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/minimal-rain.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/model-optimizations-and-fixes.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/nether-bricks-fix.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/no-z-fighting.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/sodium-translations.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/trapdoor-fix.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/unique-enchanted-books.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/visual-potions.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/wpila.pw.toml"
metafile = true

[[files]]
file = "shaderpacks/BSL_v8.2.07.1.zip.txt"

[[files]]
file = "shaderpacks/ComplementaryReimagined_r5.1.1.zip.txt"

[[files]]
file = "shaderpacks/ComplementaryUnbound_r5.1.1.zip.txt"

[[files]]
file = "shaderpacks/bsl-shaders.pw.toml"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
metafile = true

[[files]]
file = "shaderpacks/complementary-unbound.pw.toml"
metafile = true
