name = "AchieveToDo"
author = "diskree"
version = "1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "78f3980c113ce00e7bcfaec07723091cfd374d25587785a8950f600c410950c3"

[versions]
minecraft = "1.20.1"
quilt = "0.19.5"
