name = "AchieveToDo"
author = "diskree"
version = "1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ddda645dc6912158350aaf6b4d74e776b13ffc7c09567fe788945527651e93b3"

[versions]
minecraft = "1.20.1"
quilt = "0.20.1"
