name = "AchieveToDo"
author = "diskree"
version = "1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3600a2eca7d759a39ea307cd2b1f5e14cbb7a1307197bf24fe87937b4b27ea10"

[versions]
minecraft = "1.20.1"
quilt = "0.20.1"
