name = "${packName}"
author = "${author}"
version = "${packVersion}"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a3d721f3ad34c91d8b7dc7d3e9b55a7cf3af6097a3831a240459ce7eb2a9623"

[versions]
fabric = "${loaderVersion}"
minecraft = "${minecraftVersion}"
