name = "${packName}"
author = "${author}"
version = "${packVersion}"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "25ed2f4c295ff0e1f46a4240362b651959f25c834cd141dd2fe0c827b1920ce8"

[versions]
fabric = "${loaderVersion}"
minecraft = "${minecraftVersion}"
