name = "AchieveToDo"
author = "diskree"
version = "1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b770a000014bd5e83070dff3cec417ec8942538966a9ad5bfadc10af23604957"

[versions]
fabric = "0.15.3"
minecraft = "1.20.4"
