name = "AchieveToDo"
author = "diskree"
version = "1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3d420469086ec8775b96e8066e230572753178dca3304316c081349daa2ab45"

[versions]
minecraft = "1.20.1"
quilt = "0.19.5"
