name = "${packName}"
author = "${author}"
version = "${packVersion}"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2b851e67c9c65d1a725ac120e419ab677e3e73b725cf3c0309b16c61f891ea8e"

[versions]
fabric = "${loaderVersion}"
minecraft = "${minecraftVersion}"
