version = 3
globalExecutorParallelism = 2

[clientSideConfig]

[clientSideConfig.modifyMaxVDConfig]
enabled = true
maxViewDistance = 64

[noTickViewDistance]
compatibilityMode = true
ensureChunkCorrectness = false
updatesPerTick = 10
enabled = true

[generalOptimizations]
doMidTickChunkTasks = true
optimizeAsyncChunkRequest = true

[generalOptimizations.autoSave]
mode = "ENHANCED"
delay = 20000

[ioSystem]
async = true
chunkStreamVersion = 2
replaceImpl = true
chunkDataCacheSoftLimit = 1536
chunkDataCacheLimit = 6144

[asyncScheduling]
enabled = true

[threadedWorldGen]
allowThreadedFeatures = true
reduceLockRadius = true
enabled = true

[vanillaWorldGenOptimizations]
optimizeAquifer = true
useEndBiomeCache = true

